
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: RyanUsherTattoo_development

test:
  <<: *default
  database: RyanUsherTattoo_test

production:
  <<: *default
  database: RyanUsherTattoo_production
  username: RyanUsherTattoo
  password: <%= ENV['RYANUSHERTATTOO_DATABASE_PASSWORD'] %>
